// https://profile-summary-for-github.com/api/user/tangweikun
export const PROFILE_SUMMARY_FOR_GITHUB = {
  user: {
    hireable: true,
    createdAt: 1437030883000,
    collaborators: 0,
    diskUsage: 0,
    followers: 37,
    following: 69,
    id: 13361639,
    ownedPrivateRepos: 0,
    privateGists: 0,
    publicGists: 18,
    publicRepos: 58,
    totalPrivateRepos: 0,
    avatarUrl: 'https://avatars0.githubusercontent.com/u/13361639?v=4',
    blog: '',
    company: 'iHealth(中国)',
    email: '819573105@qq.com',
    gravatarId: '',
    htmlUrl: 'https://github.com/tangweikun',
    location: '北京市',
    login: 'tangweikun',
    name: '汤伟坤',
    type: 'User',
    url: 'https://api.github.com/users/tangweikun',
    plan: null,
  },
  quarterCommitCount: {
    '2015-Q3': 0,
    '2015-Q4': 0,
    '2016-Q1': 11,
    '2016-Q2': 192,
    '2016-Q3': 8,
    '2016-Q4': 39,
    '2017-Q1': 53,
    '2017-Q2': 25,
    '2017-Q3': 215,
    '2017-Q4': 185,
    '2018-Q1': 629,
    '2018-Q2': 445,
    '2018-Q3': 381,
    '2018-Q4': 81,
  },
  langRepoCount: {
    JavaScript: 36,
    Unknown: 5,
    HTML: 4,
    TypeScript: 2,
    Python: 2,
    CSS: 1,
    Go: 1,
  },
  langStarCount: {
    Unknown: 249,
    JavaScript: 195,
    TypeScript: 108,
    CSS: 0,
    Go: 0,
    HTML: 0,
    Python: 0,
  },
  langCommitCount: {
    JavaScript: 1214,
    TypeScript: 771,
    Unknown: 167,
    Go: 65,
    Python: 22,
    CSS: 14,
    HTML: 11,
  },
  repoCommitCount: {
    leetcode: 768,
    EMBASystem: 174,
    'Front-End-Knowledge': 149,
    wolf: 143,
    codewars: 117,
    '24-point': 106,
    ghost: 88,
    'js-basic': 79,
    'lodash-es6': 68,
    'go-go-go': 65,
  },
  repoStarCount: {
    'awesome-leetcode': 248,
    leetcode: 108,
    codewars: 68,
    'DataStructure-Algorithm': 59,
    'javascript-design-pattern': 57,
    'oath-keeper': 3,
    'lodash-es6': 2,
    api: 1,
    auth0: 1,
    'Front-End-Knowledge': 1,
  },
  repoCommitCountDescriptions: {
    leetcode: ':zap: Leetcode Solutions',
    EMBASystem: null,
    'Front-End-Knowledge': '🚀 Front End Knowledge',
    wolf: '🐺Do something for fun',
    codewars: ':beers: CodeWars Solutions',
    '24-point': null,
    ghost: 'backend with koa',
    'js-basic': null,
    'lodash-es6':
      '🎉 Curated collection of useful Javascript snippets that you can understand in 30 seconds or less.',
    'go-go-go': null,
  },
  repoStarCountDescriptions: {
    'awesome-leetcode':
      ':nail_care: A collection of awesome leetcode solutions',
    leetcode: ':zap: Leetcode Solutions',
    codewars: ':beers: CodeWars Solutions',
    'DataStructure-Algorithm': null,
    'javascript-design-pattern':
      ':building_construction: Design Pattern With Javascript',
    'oath-keeper': 'play react with storybook',
    'lodash-es6':
      '🎉 Curated collection of useful Javascript snippets that you can understand in 30 seconds or less.',
    api: null,
    auth0: null,
    'Front-End-Knowledge': '🚀 Front End Knowledge',
  },
  timeStamp: 1541212585279,
}
